name: Build BeastMode AnyKernel3

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Scarica i tuoi file modificati
        uses: actions/checkout@v4

      - name: Crea lo ZIP per TWRP
        run: |
          zip -r AnyKernel3-BeastMode.zip ./* -x "*.yml" -x "*.md" -x ".git*"
          
      - name: Sforna lo ZIP Scaricabile
        uses: actions/upload-artifact@v4
        with:
          name: AnyKernel3-BeastMode
          path: AnyKernel3-BeastMode.zip
